# Generated by Django 4.1.1 on 2022-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insite', '0002_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Health', 'Health'), ('Wealth', 'Wealth'), ('Exercise', 'Exercise'), ('Mindfulness', 'Mindfulness')], default=None, max_length=20),
        ),
    ]
